### ISSUE TITLE
parsing error when retaining top K matches.

### ISSUE THREAD

**Issue by leiwang-me** [PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter#3]
Hi PNNL folks,

Greetings! I used MSGF to search on a MSMS dataset containing 1.4M charge 1+ spectra only, with target decoy mode (`-tda 1`) and retain top 5 matches for each spectrum (`-n 5`).  Then I tried to use the MzidToTsvConverter.exe to convert mzid to tsv, using multiple methods and none of them worked.
1. I used command `mono MzidToTsvConverter.exe -mzid:${file} -sd`, where `${file}` is the respective mzid file to convert. I got errors 
2. I used command `mono MzidToTsvConverter.exe -mzid:${file} -sd -singleResult:5` and got pretty much the same error.

The errors are
``` 
Conversion failed: An item with the same key has already been added. Key:PepEv_3418638_200272_301 at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.Insert ionBehavior behavior) [0x0015a] in <47d423fd1d4342b9832b2fe1f5d431eb>:0
at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <47d423fd1d4342b9832b2fe1f
5d431eb>:0
  at PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadPeptideEvidence (System.Xml.XmlReader reader) [0x000d3] in <c35e318121b
24d90a706f5888e0514ce>:0
  at PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadSequenceCollection (System.Xml.XmlReader reader) [0x00098] in <c35e3181
21b24d90a706f5888e0514ce>:0
  at PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadMzIdentMl (System.Xml.XmlReader reader) [0x001f5] in <c35e318121b24d90a
706f5888e0514ce>:0
  at PSI_Interface.IdentData.SimpleMZIdentMLReader.Read (System.String path, System.Threading.CancellationToken cancelToken) [0x00079] in <c35e318121b24d90a706f5888e0514ce>:0
  at MzidToTsvConverter.MzidToTsvConverter.ConvertToTsv (System.String mzidPath, System.String tsvPath, System.Boolean showDecoy, System.Boolean unrollResults, System.Boolean singleResult) [0x00005] in <aa4e31edbbde478ea61c353a0c4310ee>:0
  at MzidToTsvConverter.MzidToTsvConverter.ConvertToTsv (MzidToTsvConverter.ConverterOptions options) [0x0001f] in <aa4e31edbbde478ea61c353a0c4310ee>:0
  at MzidToTsvConverter.Program.Main (System.String[] args) [0x00026] in <aa4e31edbbde478ea61c353a0c4310ee>:0
```
Could you please help me with it?   Thanks, Lei.

**Comment by alchemistmatt** [comment]
There is a duplicate item trying to be added to a dictionary; we cannot diagnose the issue without the .mzid file, so you will need to send us the file.  Send me your e-mail address to proteomics@pnnl.gov and I can send you a web link for sending us the file.

**Comment by FarmGeek4Life** [comment]
What version of MS-GF+ did you use? There have been a couple more recent updates to combat this problem (because this is a problem with MS-GF+, not so much with this converter).

As a workaround (with a cost of maybe losing some detail, depending on the version of MS-GF+), you can add the flag `-skipDupIds` to the command line to ignore the duplicate IDs.

**Comment by leiwang-me** [comment]
> What version of MS-GF+ did you use? There have been a couple more recent updates to combat this problem (because this is a problem with MS-GF+, not so much with this converter).

I used MS-GF+ Beta (v10089) (7/16/2014).  I originally asked in this thread https://github.com/MSGFPlus/msgfplus/issues/14 and I went with what you suggested for converting mzid to tsv file. 

> As a workaround (with a cost of maybe losing some detail, depending on the version of MS-GF+), you can add the flag `-skipDupIds` to the command line to ignore the duplicate IDs.

What would this flag `-skipDuplds` lead to? We would love to retain the top 5 matches in the tsv file after conversion.  
Matthew suggested to upload my mzid and I will upload it once I get the upload link from him. Thanks Bryson!

**Comment by FarmGeek4Life** [comment]
If you look at the [MS-GF+ releases page](https://github.com/MSGFPlus/msgfplus/releases), we place release notes there about what has changed or what bugs have been fixed compared to the previous version. The version you are using (v10089) has a number of problems with duplicate Peptide and PeptideEvidence IDs, even when only keeping the top match. There have also been a number of other fixes in that time. I would suggest you re-run the search with the latest version of MS-GF+ available ([Release 2019.04.18](https://github.com/MSGFPlus/msgfplus/releases/tag/v2019.04.18), because that will probably fix the entire problem.

**Comment by leiwang-me** [comment]
We are reruning the whole search with the latest  version Release 2019.04.18, Thanks for the great help!

**Comment by leiwang-me** [comment]
Hi there,

I ran into errors when parsing mzid to tsv using the latest version of MzidToTsvConverter inside MSGFPlus_v20190418. The output and errors are
```
Using options:
mzid path: "/home/data/wang558/PXD000561-full/msgf_results/mzid/raw/3_full_PXD000561.carbonate.uniprot.tda0.top5.mzid"
tsv path: "/home/data/wang558/PXD000561-full/msgf_results/mzid/raw/3_full_PXD000561.carbonate.uniprot.tda0.top5.tsv"
Unroll results: False
Show decoy: True
Single result per spectrum: False
No filters are in use

------------------------------------------------------------------------------
MZID PARSE ERROR: Cannot add duplicate peptideEvidence id "PepEv_320323_290041_27"!

Stack trace: 
  MzidToTsvConverter.MzidToTsvConverter.ConvertToTsv 
  PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadLowMem 
    at PSI_Interface.IdentData.SimpleMZIdentMLReader+<ReadMzIdentMl>d__28.MoveNext 
  PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadSequenceCollection 
  PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadPeptideEvidence 
------------------------------------------------------------------------------

MZID PARSE ERROR: Cannot add duplicate peptideEvidence id "PepEv_320323_290041_27"!

This type of error is usually caused by an error in the MZID output
```

Any ideas?  Thanks!

**Comment by FarmGeek4Life** [comment]
This is a problem with the version of MSGFPlus you used. PeptideEvidence id "PepEv_320323_290041_27" is in a format no longer used (the code was changed to use a different format in December 2014), which tells me you are using probably version v10072 or v10089. 

Please try your search again with the current version of MS-GF+, which is inside the zip file you downloaded. It includes fixes for the error you see above, which is a problem seen with certain old versions of MS-GF+ (it is actually an invalid mzid file, since there are duplicated IDs in the file).

If you still have problems with a file produced by the current version of MS-GF+, then we do have a problem that hasn't been fixed.
