### ISSUE TITLE
Bug with -singleResult

### ISSUE THREAD

**Issue by tivdnbos** [PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter#4]
Hi,

When trying to convert my mzid files the Mzid Converter, I would like to use the -singleResult option (or -1), but then one result is written to the tsv per mzid, instead of per spectrum. How can I solve this? Also, on which criterium does it select the best match? Is this the Q-Value?

Many thanks in advance!

**Comment by FarmGeek4Life** [comment]
Can you attach/share one of the mzids that is exhibiting this issue? That will be necessary to determine what is causing this issue.

**Comment by tivdnbos** [comment]
[pyro_pyro.mzid.zip](https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/files/3262664/pyro_pyro.mzid.zip)

**Comment by tivdnbos** [comment]
Thanks for checking it! Can you also comment on how the convertor chooses which peptide per spectrum it takes?

**Comment by FarmGeek4Life** [comment]
It takes the first one that appears in the file for that spectrum; MS-GF+ outputs the highest-scoring (by specEValue) result first.

**Comment by FarmGeek4Life** [comment]
This single-result-for-the-file problem is due to some missing information in the MGF; MS-GF+ normally outputs the spectrum index (in the file) as the 'spectrumID' for each SpectrumIdentificationResult, and then adds a CV Param to it that is the original spectrum number, if it can read it; the MzidToTsvConverter didn't properly handle the case where MS-GF+ isn't able to get the original spectrum number, and therefore does not output that CV Param. I am changing that code to check for that case and instead use the parsed spectrum index for these checks.

**Comment by FarmGeek4Life** [comment]
Fixed with a [PSI_Interface commit](https://github.com/PNNL-Comp-Mass-Spec/PSI-Interface/commit/0fa95c66a79a0dbbb564d773a2e172d648628a20) and [DLL update](https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/commit/9b0c606282ba8380e7099739855f6594b55c48ac). Download fixed binaries with [Release Version 1.3.2](https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/releases/tag/v1.3.2)
